APPLICATION_NAME = "fastapi_postgres_backend"
LOG_HEADER = f"{APPLICATION_NAME}_log"
TESTING_ENVIRONMENT = "testing"
PRODUCTION_ENVIRONMENT = "production"
DEVELOPMENT_ENVIRONMENT = "development"
ENV_ERROR = "invalid environment: {}"
